name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest

    env:
      TODOIST_EMAIL: ${{ secrets.TODOIST_EMAIL }}
      TODOIST_PASSWORD: ${{ secrets.TODOIST_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test